[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; A BLE stack nagy, a default partíció kevés lehet
board_build.partitions = huge_app.csv
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
